#!/usr/bin/env bash
# Regenerate Wordbreak's favicon / app-icon / social-preview assets in public/
# from the editable SVG masters in assets/.
#
# Requires: rsvg-convert (librsvg) and magick (ImageMagick).
#   brew install librsvg imagemagick
#
# The masters are the single source of truth — tweak the amber (#e0af68) or
# geometry there, then re-run this. Nothing here is generated by hand.
set -euo pipefail
cd "$(dirname "$0")/.."

ICON="assets/icon.svg"            # rounded mark, transparent corners (browser favicon / web icons)
FB="assets/icon-fullbleed.svg"    # edge-to-edge bg (iOS re-masks corners; Android maskable safe-zone)
OG="assets/og.svg"                # 1200x630 social card
OUT="public"
mkdir -p "$OUT"

echo "==> favicon.svg (vector, primary)"
cp "$ICON" "$OUT/favicon.svg"

echo "==> rounded PNGs"
for s in 16 32 48 192 512; do
  rsvg-convert -w $s -h $s "$ICON" -o "$OUT/icon-$s.png"
done
cp "$OUT/icon-16.png" "$OUT/favicon-16.png"
cp "$OUT/icon-32.png" "$OUT/favicon-32.png"

echo "==> favicon.ico (16/32/48 multi-res)"
magick "$OUT/icon-16.png" "$OUT/icon-32.png" "$OUT/icon-48.png" "$OUT/favicon.ico"
rm -f "$OUT/icon-16.png" "$OUT/icon-32.png" "$OUT/icon-48.png"   # rolled into favicon.ico / favicon-*.png

echo "==> apple-touch-icon (180, full-bleed) + maskable (512, full-bleed)"
rsvg-convert -w 180 -h 180 "$FB" -o "$OUT/apple-touch-icon.png"
rsvg-convert -w 512 -h 512 "$FB" -o "$OUT/icon-maskable-512.png"

echo "==> og.png (1200x630 social preview)"
rsvg-convert -w 1200 -h 630 "$OG" -o "$OUT/og.png"

echo "done. assets written to $OUT/"
